spring:
  application:
    # 服务名
    name: service-consumer
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: localhost:8848

server:
  port: 8001

management:
  # 端点检查
  endpoints:
    web:
      exposure:
        include: "*"
